[2024-07-24T09:54:36.769+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:54:36.840+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T09:15:00+00:00 [queued]>
[2024-07-24T09:54:36.871+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T09:15:00+00:00 [queued]>
[2024-07-24T09:54:36.872+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:54:36.899+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 09:15:00+00:00
[2024-07-24T09:54:36.912+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=897) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:54:36.932+0000] {standard_task_runner.py:64} INFO - Started process 947 to run task
[2024-07-24T09:54:36.938+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T09:15:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmphtumf093']
[2024-07-24T09:54:36.941+0000] {standard_task_runner.py:91} INFO - Job 213: Subtask database_connection
[2024-07-24T09:54:37.088+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T09:15:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:54:37.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T09:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T09:15:00+00:00'
[2024-07-24T09:54:37.454+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:54:37.455+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:54:37.456+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:54:37.572+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:54:37.589+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:54:37.590+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:54:37.591+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:54:37.671+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T09:15:00+00:00, execution_date=20240724T091500, start_date=20240724T095436, end_date=20240724T095437
[2024-07-24T09:54:37.911+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:54:37.940+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:54:37.949+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
