[2024-07-24T09:54:30.906+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:54:31.048+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T08:15:00+00:00 [queued]>
[2024-07-24T09:54:31.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T08:15:00+00:00 [queued]>
[2024-07-24T09:54:31.081+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:54:31.188+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 08:15:00+00:00
[2024-07-24T09:54:31.220+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T08:15:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmp3l_luxbb']
[2024-07-24T09:54:31.196+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=880) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:54:31.230+0000] {standard_task_runner.py:64} INFO - Started process 914 to run task
[2024-07-24T09:54:31.223+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask database_connection
[2024-07-24T09:54:31.527+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T08:15:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:54:32.359+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T08:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T08:15:00+00:00'
[2024-07-24T09:54:32.363+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:54:32.366+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:54:32.369+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:54:32.423+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:54:32.431+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:54:32.444+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:54:32.445+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:54:32.501+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T08:15:00+00:00, execution_date=20240724T081500, start_date=20240724T095431, end_date=20240724T095432
[2024-07-24T09:54:32.592+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:54:32.659+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:54:32.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
